# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 170ec73243ef6ba688b3ca34c8d7aa77eb9b105a1cee5cf0049d2a0dd377490c55f8fbf1a9e81436af4ed70a33f76de361cda036edc28008c9cc9fb8519fefaa

test:
  secret_key_base: c30059ac0f35c36ee906debdeff9262de2913d6ada85978d38a00306b2cb006ed76d39125a171cd3f0e2d9a27ad6adbf95dfbda45b426bba8a75a0672527c305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
